### ISSUE TITLE
staking 

### ISSUE THREAD

**Issue by bang121** [monyxcoin/monyx-coin#131]
ref with previous issue link:  https://github.com/monyxcoin/monyx-coin/issues/130

then how it is possible 10 % per month in last 58 hr i have just received 1.59 coin. how u calculate 10% staking reward ? as per calculation it should be .75%return and till now i have received 1.59 coin.  please explain in details. thank you in advance @monyxcoin

**Comment by monyxcoin** [comment]
@bang121 PoS reward scales with the coin age, it's made like so because 1) otherwise the total 24m limit of coins will be depleted really fast, 2) with more and more wallets running there will be more and more possible candidates for a new PoS block, so all other possible candidates getting older and will receive bigger reward (scaled with the coin age).
That's how it's done in every coin, as for example davorcoin: https://github.com/davorcc/DavorCoin/blob/master/src/main.cpp#L1012.

You can see the algorithm here:
https://github.com/monyxcoin/monyx-coin/blob/master/src/main.cpp#L973

You can read more on how PoS works here: https://github.com/novacoin-project/novacoin/wiki/Proof-of-stake
