### ISSUE TITLE
1.80 floor price removed? Deposit not working?

### ISSUE THREAD

**Issue by alexpride007** [monyxcoin/monyx-coin#17]
please explain why the $1.80 floor price was removed and why after 6 confirmations deposit still not going through?

**Comment by monyxcoin** [comment]
I'm not responsible for the decision the team working on exchange makes, sorry.

Regarding the missing deposit: what is the tx id?

**Comment by wah0004** [comment]
Hi Dev, my deposit is also not showing. Looks like it has been redirected to Monyx main wallet?

Tx ID: af0b194d3d8147e014fe5ab4943e21480d87cb2965b2c378cfe5310ce0ad2a23

Link: https://live.blockcypher.com/btc/tx/af0b194d3d8147e014fe5ab4943e21480d87cb2965b2c378cfe5310ce0ad2a23/

Thanks!

**Comment by monyxcoin** [comment]
Thanks, will take a look. In any case all missing transactions will be deposited, so don't worry.

**Comment by xStarBlade** [comment]
Are you guys going to allow whales to buy at this price??

**Comment by monyxcoin** [comment]
@xStarBlade as I said, I'm not responsible for the decisions the exchange team makes, but if I understood them correctly, they removed the price limit due the multiple reasons: 1) to make the market more active, 2) due the current BTC/cryptocurrencies state, 3) as they told me "we don't force anybody to sell at such a low price".

Anyway the price is expected to go higher once lending is released (should be around the end of this month, most likely earlier, but the main thing right now is to stabilize the exchange, since it's pretty complex system).

That's all the information I got from them.

**Comment by alexpride007** [comment]
Tx ID: 9731c804ab4981bcb9338ea5a116e663dbb10aff65c560870f6e8e91cd5677fc  

pls look into this..

**Comment by monyxcoin** [comment]
@alexpride007 @wah0004 resolved
