### ISSUE TITLE
Give back my BTC taken

### ISSUE THREAD

**Issue by animalmode** [monyxcoin/monyx-coin#201]
Hello, You took too much money out of my account. I put 0.06661867 in
on the 7th feb Then withdrew 0.01951838 and 0.06661867 on the 7th feb.
I did not know there was a glitch. I sold my monyx coin and you took all my BTC from that too.

I am owed 0.04710029 BTC please fix asap.

**Comment by chakramchirkut** [comment]
They are working overtime and under the pump, it will be ok..its still better than getting 404 site not found :0
The hot wallet for BTC will be funded again and the audit will fix the balance etc.

**Comment by monyxcoin** [comment]
@animalmode i see that because of the bug you got `0.12331253` more BTC than needed and bought `1545.65727392` MYX with those BTC. Then you withdrew all MYX. Then you sold 2 times 1000 MYX and got about `0,08551` BTC but that's not enough to cover that amount that you got because of the bug.

So I don't see how we could take more money from you than needed. You still owe us about 0,04 BTC.

**Comment by manojaum** [comment]
Lol. nice catch :)

**Comment by manojaum** [comment]
@monyxcoin maybe wait for some more time, if he makes some more purchases or sell at higher price, u can take it from him 💃
