### ISSUE TITLE
Guys please realize your money is scammed

### ISSUE THREAD

**Issue by debow22** [monyxcoin/monyx-coin#208]
You guys took in hundreds of BTC during the ico. These excuses are so lame!!! Just exit already.

**Comment by chakramchirkut** [comment]
If you dont have patient then sell your coins mate, why create FUD for nothing, did you see the number of tickets and number of instances where devs are helping ? 
I care for my investment and so do others..so keep the FUD to yourself.

**Comment by IamTheM8** [comment]
just sell if you don't like monyx, don't worry real investors will buy your coins

Best for you m8, @debow22

**Comment by chakramchirkut** [comment]
@debow22  Mate, can i please ask you to close the ticket. If you want to Vent your frustration please do it on Telegram non official group..atleast leave Github Issues separate.

**Comment by chass3768** [comment]
IF they were going to exit scam, they would of already done it, you big dummy!

**Comment by marcelvan** [comment]
PLEASE CLOSE THIS TICKET


cry babies shouldnt be in crypto full stop lol sell up an move on champ

**Comment by monyxcoin** [comment]
I, the developer, am pretty sure the platform won't be closed and money are not taken by the team, since we still have some communication. There is a delay with announcing new information, because it took more time for them to determine a new direction, start preparing things, etc.

Unfortunately it seems we'd need to wait like another week, but again, we have pretty big amount of premined MYX as founders and it's really in our interest to make the price higher (who would want to lose like 6 figures potential earnings?).
So I'm sorry it takes so long, there is nothing I myself can change, only keeping the exchange working and fixing bugs.
