### ISSUE TITLE
Error or the hot wallet is empty and soon will be funded ?

### ISSUE THREAD

**Issue by alexpride007** [monyxcoin/monyx-coin#219]
Error or the hot wallet is empty and soon will be funded ? i'm getting this errorr.. pls look into it

username: alexpride

**Comment by JamjamMcjammerson** [comment]
The hot wallet is only loaded with so much for security reasons. Monyx refills it everyday, just try again later.

**Comment by TonyMcclure** [comment]
"The hot wallet is only loaded with so much for security reasons. Monyx refills it everyday" 
 When/where did u see that? I didn't get that reply here with my support ticket, like 2 days ago. That was deleted btw. Else I would have said. Hay, there's already a ticket for this lol. 
 I have just over 6,000 myx, most from the ICO @ $.7 to a 1.00. & I know they lost 20 BTC. But their website says it's all been  sorted. So, that shouldn't have anything to do with our BTC. 
& that's a  huge red flag, but we need to give them at least through the 20th before anyone really loses their heads lol. Cause they will  either buy back tokens or disappear lol. But we know the risk so stop crying. 
 If ur not in the most active telegram group https://t.me/MonyxOpenGroup . Come see what's happening. Most of us r bullish. & this is our only  concern. Cause if they can't give us our BTC now. How r they going to buy back MYX? 
 & don't rage this GitHud guy. He probably won't even know when they exit if they do lol. 
 But u knew what u was getting into & if u didn't, u do now. 
 I could just go on forever lol. Like why don't they use the bot to make up the BTC while they're not playing  interest?

**Comment by JamjamMcjammerson** [comment]
There have been many tickets about the empty hot wallet issue and they all get closed because they get resolved the next time the hot wallet is filled. Monyx can’t waste their time replying to the same ticket that’s been answered 10 times already. Also, the error message you received explains the problem (it’s empty, wait for refill). I understand that people are very nervous because so many lending platforms are folding up shop so if any problem happens people panick but that doesn’t help anybody. Either trust the platform you’re invested in and be understanding of problems when they arise, or if you have no trust left either ride it out and see what happens or sell your coins and cut your losses.
