### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by Palkkari** [monyxcoin/monyx-coin#224]
So, I have read that you are (just like all of us) waiting for the team to release some information about the future of this project. My question is: Do you have any information from them that we don't already know. I mean, have they told you that there will be delays or something? It would be good for us to know, even if the update was that there will be a slight delay with the buyback plan or something. Also, are you communicating with the team everyday? If so, what was the latest news that you got from them? Alot of questions I know, but I would appreciate if you take your time to answer these. Thanks!

**Comment by monyxcoin** [comment]
Unfortunately the guy from the team I'm usually communicating with wasn't really active last week, I was getting just few messages from him, nothing really interesting, no idea what's the plan. 
They also hold the cold wallet, so I can't really fill the hot wallet in time, still waiting for them to compensate the amount we lost due the bug (that later will be returned back to them once the MYX price is higher and we sell the deducted MYX), that's why hot wallet is usually empty recently.

So the only thing I do is just keeping the exchange functional, fixing bugs, implementing some small new features.
Also if I understand correctly, they don't really check the support email (me neither, since I don't have access to it). But for that soon a ticketing support system will be implemented.

The only thing I know is that listing on external exchanges will happen for sure and the platform won't be closed or abandoned.

**Comment by xStarBlade** [comment]
Can you disclose if you all live in Switzerland? Some people are worried that the dev team is split up across the world.

**Comment by Palkkari** [comment]
@monyxcoin
Thank you for answering!
One more thing, could you ask them to update us on their official social media (twitter and telegram)? Communication is one of the most important things with these programs. If you have already asked them to do that, what did they answer to you? Thank you!

**Comment by chass3768** [comment]
@xStarBlade What difference does it make where they all live at lmmfao! I could care less if they all lived on different planets, as long as this platform launches fully, and I can make some more money!

**Comment by Blitzkitten** [comment]
Yeah I gotta agree, global location is a bit of a nothing..

I'm involved in a coin and our dev team comes from: Australia, China, Holland, Finland, Germany & USA..

**Comment by xStarBlade** [comment]
Both of you need to think harder about this before foolishly dismissing it as nothing. It is massively important whether they live in Switzerland or not. 1. If not, they are liars out of the gate, and should have just stuck to not mentioning their location. 2. If they all live within driving distance it means they likely have met each other in person which is very important, because if you have been paying attention to scams  lately, then you should  know it is not unheard of for one team member to go rogue and steal funds and tank the platform. If none of the members know the identity of each other, or if this dev does not know the core team personally, then if they happen to quit the project  for some reason, it means there is 0% chance of anyone getting money back or finding the dev team. Whether either of you two care is completely irrelevant, I did not ask for your opinions. The point is that other investors would like to know. The scam/fail percentage of these platforms is nearly 100%, so us knowing if the dev team knows each other personally or not is important, because as of now we know this dev is just a contractor, and yet he seems to be the most interested in doing any work. If he knows them personally and can vouch for their sincerity then that goes a long way.
