### ISSUE TITLE
GIVE ME BACK MY BTC DEPOSIT!!!

### ISSUE THREAD

**Issue by elle1203** [monyxcoin/monyx-coin#227]
My Account was affected by the Bug and I got 0.05099975 BTC. And You have corrected that already, But before the Bug I deposited 0.02548569 BTC, Where is it ?!!!
TXID: 2607a1d4fe0e0162a4a89a1e3956be1ac6c52b2285a3e8643e6c8c1600145212

Account Username:
elle1203
![monyx](https://user-images.githubusercontent.com/36538855/36343910-7d013952-144d-11e8-99b2-ccdb158b2103.png)
![monyx1](https://user-images.githubusercontent.com/36538855/36343913-8120953c-144d-11e8-8e8e-2edfb1848c23.png)

Yes You Have Corrected the Bug, You have Deducted the 0.05099975 BTC, But You Have also deducted my Previous Deposit!!!

**Comment by monyxcoin** [comment]
@elle1203 investigating.

**Comment by monyxcoin** [comment]
@elle1203 I see that first you used your first deposit to buy 195 MYX and had in total 215 MYX.

Then with your second deposit you bought 424 MYX and then with the amount that you got because of the bug you bought another 867 MYX.

I'll restore you the initial MYX amount that you would have after first made order, so in total 215 + 424 = 639.
