### ISSUE TITLE
The use case for MYX

### ISSUE THREAD

**Issue by goldnpower** [monyxcoin/monyx-coin#228]
Hey, I've been looking at a lot of lending platforms throughout the last few months, my though is that this era is coming to an end.
This is why I'm asking the @monyxcoin team, why don't you make the MYX use case for staking only? 0.5%-1% staking reward or like 20% per month or something, would skyrocket the price of the coin as well, then implement more use cases as time goes

**Comment by kamillasecki** [comment]
Simply because with staking you are lending your coins, and not USD value of it. Therefore, with regular lending scenario, the company was able to pay out interest base on the assumption that capital release will release USD value of lending. Let’s say you have lend them 500 coins at 2$ value each, you have lent 1000$ but your money is locked for 100+ days, this is to allow a coin to raise its value. If the coin increased its value from 2$ to 10$ over this time, your capital release was just 100 coins, therefore company have been now left with 400 coins worth at this stage 4000$. 

With staking only, company would have to 'print' new coins all the time to pay for it and with the rates you are proposing it would mean that there would be 20% more coins more on the market every month. Therefore, the price of the coin would keep dropping. 

The only options I can see for those companies is to implement lending as we know it, and maybe rename it to something else that does not have a bad fame or keep investing our funds and multiplying them rather by developing their trading bots, or other ways.

**Comment by anasyd0205** [comment]
i have a problem here i dont do any selling monyx or do withdrawal balance for MYX and BTC but why my balance is zero and then why inside withdrawal history i wd my btc balance . and before 7 february i dont have that history so whay i have that history now, can you restore my balance or this do with a bug?

**Comment by anasyd0205** [comment]
do you have bad security i thing do you have good security with what you said in your platflom and monyx support?

**Comment by Palkkari** [comment]
@anasyd0205
I guess someone hacked you account, sold your MYX and withdrew BTC to his wallet. Do you use 2FA, I'm afraid you don't. If you don't use 2FA, and someone hacked your account, Monyx can't help you I guess.

**Comment by anasyd0205** [comment]
I dont use.I want to buy more monyx but i am still has trauma. But can
expect minus has high price if i buy monyx now?

Pada tanggal 18 Feb 2018 10.40 PM, "Palkkari" <notifications@github.com>
menulis:
