### ISSUE TITLE
E-mail Issue Again :(

### ISSUE THREAD

**Issue by t971005** [monyxcoin/monyx-coin#233]
Hey this is username JCDenton again

I recently was having trouble getting the email for monyx withdrawal, I believe it is related to microsoft so please

Change my e-mail to the following: JCdenton1@protonmail.com

thank you for your assistance monyx support

**Comment by monyxcoin** [comment]
@t971005 done.

**Comment by monjil43** [comment]
My withdraw is not working why??  User name:  Monjil43

On 18 Feb 2018 5:01 pm, "monyx.io" <notifications@github.com> wrote:

@t971005 <https://github.com/t971005> done.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/monyxcoin/monyx-coin/issues/233#issuecomment-366509482>,
or mute the thread
