### ISSUE TITLE
Before you guys get ahead of yourselves.

### ISSUE THREAD

**Issue by xStarBlade** [monyxcoin/monyx-coin#251]
I know you (github dev) don't make the decisions here, but since you guys do not pay attention to the market sentiment on your coin beyond this website, I'd like to point out people are furious about this decision you guys arbitrarily made. I implore you guys to have a public poll to decide the future of this platform. It is one thing to have a casino on the side, but no one currently invested in this is excited about a crypto casino for which we have no good example to point to so that we can say oh yes that will succeed. My point is, please get investor feedback on this before potentially crushing your own platform. A poll would be very much  appreciated. You guys can promote the poll on facebook, twitter, and telegram. I think you will find that what I am saying is true. We believed in you and supported you guys this whole time, so I think listening to our voices is important. Please  relay our issue  to the team. Thank you!

**Comment by manojaum** [comment]
casino is horrible and that too May month, what are we gonna do next 3 months with monyx tokens then. Start the buy back plan tomo and please buy my coins back at 3$ (you mentioned 2-5$ )

**Comment by monjil43** [comment]
they can't because they want money only. sucks platform.

**Comment by Velorx95** [comment]
i agree with this very much. They said they would have transparency with the community and then they completely do a 180 turn. We didnt invest into a casino project, but doesnt mean we do not want it. Why not have the best of both worlds with a staking AND casino project. People could gamble their interests in casino games etc... Never say you are gonna be completely transparent with your community and then leave us in the dark. You have to reconsider because no one is happy and no one will be happy in the future with out changes now and not later down the road. We dont want to wait another week, another month etc for an announcement. Make an announcement with changes ASAP. I agree with the poll strategy.

**Comment by Blitzkitten** [comment]
Amen brothers!

**Comment by cryptobulot** [comment]
btc withdrawal  is the big problem
 they need to refill their wallet first.....
