### ISSUE TITLE
funds correction

### ISSUE THREAD

**Issue by GCAR1** [monyxcoin/monyx-coin#270]
My account was Not compromised, as noted below. Please correct the amount of MYX or the equivalent deposit of BTC back into my account. You can see my deposits in my deposit history. 

"Important Notice: 
You are one of the users whose balance was affected by the bug in the system and therefore got 0.xxxxxx BTC. 
To correct your balance we deducted: 0.xxxxxxxx BTC and xxx.xxx00000 MYX (equivalently to missing BTC amount based on MYX price = 0.xxxxxx BTC). "

Username GTC

Thank you,
 GTC

**Comment by Blitzkitten** [comment]
Did you get BTC credited by mistake from the bug?

If you did and you subsequently bought MYX with those funds the 'team' took back the current BTC value that you were credited for... and because MYX has dropped in price it means they took more MYX than you would have bought..

I don't agree with this at all, but I'm fairly sure that is the method of reallocating funds.

It is basically a case of: the bug in our system is going to cost you... not us

**Comment by Blitzkitten** [comment]
I personally cannot.. I'm no authority on the matter.

The @monyxcoin guy is very helpful when errors like this have arisen. Hopefully he comes and helps you out
