### ISSUE TITLE
my coins are gone

### ISSUE THREAD

**Issue by juliac-toronto** [monyxcoin/monyx-coin#273]
Hello Monyx admins! I received this message in my back office: 
--------------------------------------------------------------------------------
Important Notice: 
You are one of the users whose balance was affected by the bug in the system and therefore got 0.01871637 BTC. 
To correct your balance we deducted: 0.00004635 BTC and 466.75050000 MYX (equivalently to missing BTC amount based on MYX price = 0.00004 BTC).
------------------------------------------------------------------------------
Please check my transactions, all deposits in my history and i should have 758 coins and not 291. Please correct Monyx coins I have or transfer BTC deposits back to my wallet. All my deposits are registered on the blockchain. 

My username is mibhealth. 

Thank you for looking into it!

**Comment by Blitzkitten** [comment]
Did you get BTC credited by mistake from the bug? 

If you did and you subsequently bought MYX with those funds the 'team' took back the current BTC value that you were credited for... and because MYX has dropped in price it means they took more MYX than you would have bought..

I don't agree with this at all, but I'm fairly sure that is the method of reallocating funds.
