### ISSUE TITLE
withdrawals

### ISSUE THREAD

**Issue by cryptotjapkes86** [monyxcoin/monyx-coin#284]
I've tried withdrawing my BTC from monyx to coin exchange about 5 times now and it won't transfer, yes I've confirmed via email. whats going on?

**Comment by chass3768** [comment]
LOL go read the other posts about this. IF it says error hot wallet empty then you are not withdrawing anything at this point!

**Comment by JamjamMcjammerson** [comment]
Hot wallet hasn’t been funded in almost 4 days. Unacceptable

**Comment by chass3768** [comment]
I'm thinking it wont be funded again, until they recover all the bitcoin lost from the exploited bitcoin glitch on the exchange the first day. You can thank the asshole thieves that exploited the glitch and withdrew a bunch of bitcoin in a hurry the first day of the exchange!

**Comment by JamjamMcjammerson** [comment]
Chass that doesn’t make sense. They lost 20 btc and already recovered some of it. They have hundreds more bitcoin from the ICO and all the extra bitcoin that’s been deposited since then in their possession (about 160btc in volume traded so far). There is ZERO reason not to refil the hot wallet at least once a day. Also the bug has been resolved so the issue is no longer there.

**Comment by t971005** [comment]
Chass3768 is going down with the titanic because he is low IQ
