### ISSUE TITLE
Almost 4 days since the hot wallet was last funded

### ISSUE THREAD

**Issue by JamjamMcjammerson** [monyxcoin/monyx-coin#288]
This is unacceptable and needs to be publicly addressed.

**Comment by chass3768** [comment]
LOL good luck with that! Try blaming the bitcoin thieves that exploited the exchange bitcoin glitch the first day of the exchange.

**Comment by anyagixx** [comment]
@chass3768  This is a false statement, try to prove it!!!

**Comment by chass3768** [comment]
LMAO false statement my ass!

**Comment by chass3768** [comment]
I saw the glitch myself and reported the damn thing, instead of exploiting it like the damn thieving scum did asshole!

**Comment by snicksand** [comment]
I, too, saw and reported, but now understand, that for good reason not exploited

**Comment by anyagixx** [comment]
@snicksand @chass3768 
And that allowed to make this vulnerability??

**Comment by snicksand** [comment]
I think programmers made a mistake when updating scripts

**Comment by snicksand** [comment]
buying myX coins, coins were bought and bitcoin doubled on balance

**Comment by langganijen** [comment]
they use BTC to buy LTC for fork... waiting to convert there LTC fro LCC... . just my opinion.

**Comment by snicksand** [comment]
It's possible, but unlikely.

**Comment by JamjamMcjammerson** [comment]
Monyx has stated they’ve resolved the bug, there is NO reason not to be filling the hot wallet at least once a day.

**Comment by snicksand** [comment]
the error was resolved on February 7

**Comment by anyagixx** [comment]
@snicksand All signs of fraud

**Comment by snicksand** [comment]
Only time will tell. If 2-3 days without news, it means SCAM

**Comment by snicksand** [comment]
they waited for people to buy more coins on the exchange. They do not have 413 bitocons, much more ... People buy more coins in the hope of earning

**Comment by snicksand** [comment]
bitcoins*

**Comment by t971005** [comment]
Lol. They filled the hot wallet with .3 bitcoin once, used the withdrawals as "proof" of legitimacy. 
They did the same thing during the ICO. The filled the books with fake buy orders,
 there were only actually about 1.2million monyx distributed to actual people. 
The other coins were distributed back to monyx. 
Its a shame because they could have used this market control to make the price 10 dollars extremely easily, but since they live in Nigeria, they just took the money and ran. Because they are kings in their country now.
