### ISSUE TITLE
Dashboard Typo

### ISSUE THREAD

**Issue by CryptoSums** [monyxcoin/monyx-coin#33]
**What your dashboard message displays:** 
"Withdraws and deposits for MYX will be turned on tomorrow, so you will be able to start **_stacking_** with your wallet."

I'm assuming that should say "staking" instead of stacking. Also your whitepaper says we will be able to stake on our web wallets as well as desktop wallets. Is this still the case?

**Comment by monyxcoin** [comment]
@CryptoSums thanks.
Unfortunately staking on web wallet won't be available at the start, because it means we'd need to keep all private keys for each user address on the server. To avoid security issues, for now staking is available only via standalone wallets.

Once we are done with stabilizing exchange and lending, we'll look into this thing again, might implement staking on web wallets with proper security.
