### ISSUE TITLE
IMPORTANT: Community wish list

### ISSUE THREAD

**Issue by alexpride007** [monyxcoin/monyx-coin#45]
We KNOW that you're all working hard behind the scenes and we congratulate you all for the hard work done so far on the exchange and wallet. We as the community wud also like to thank  Github Dev who has been awesome and yes he does need a pay rise  :) 

Please provide the public with the following updates:

1) Officially announce when Lending platform will be released (Via Dashboard/Telegram wud be great)
2) Plans moving forward - e.g updated roadmap? Future exchanges? A dedicated help desk?
3) Is the BUY-BACK PLAN still on the table or has there been a change of plan since the price did dip to as low as 0.1 cents

Please do provide an official updated answer to all the above questions as this will erase FUD and bring back confidence to those weak hearts.

In loving memory, yours truly
Carlos Matos
xox

**Comment by monyxcoin** [comment]
@alexpride007 I'll send this issue to the team, I hope we'll be able to answer to the questions during next 1-2 days.

**Comment by CryptoGirl88** [comment]
I agree! We are ALL behind you Monyx!! If I could add to the above... I like receiving notification via Dashboard. That said, it would be great to receive via email, as well. This would keep those who need to be in the know - in the know, and those who just want to rant - ranting at themselves. Also, you wouldn't have to worry about getting to all the social media sites, which seems to lead to inconsistency when there is a lot going on. Thank you in advance. Looking forward!!!

**Comment by VM4ROI** [comment]
Now would be an amazing time to implement a lending program that makes sense for the current crypto climate, so this is what we propose that you do to get the coin moving in the proper direction!

We simply need to give the YouTuber's something to talk about...

First, I would snatch some thunder by implementing immediate lending at competitive rates for all new money/coins loaned & announce that the return of payments will be available via btc withdrawals. (this will bring in the new btc needed to pay out in btc to all investors that lock in the new loans)

Second, I would announce extremely competitive rates for staking and have the staking locked for 15, 45, & 90 days with different rates/bonuses for each. (this will further lock-in coins and reduce the total supply allowing for the price per coin to rise)

Last, announce that you plan on marketing to new investors via different platforms. We need to bring in new money as fast as possible or you will lose the trust of the people at which point you will never recover. With all of the issues and fuckery that we as investors have already endured with your platform, I feel it is necessary for you to announce something that will bring your platform to the forefront immediately! (this will spur consumer confidence in investors and YouTuber's that have already been screwed by your glitches & lack of understanding when it comes to properly promoting your exchange launch/platform)

Right now, your inaction to address the wallet issues and your inaction to address the dumping of your coin to $0.01 has a lot of us feeling uneasy about your integrity to fulfill the mission? Your last Telegram message was on the 5th of February as if nothing has changed since then? I feel that we as a community have been very patient with MonyX and only ask that you take into consideration what we feel will improve the chances of your coin succeeding and that you improve your communication with the very investors that have trusted in you from the beginning...many of us sacrificing Christmas with our families to purchase your tokens and although we aren't expecting a $20 coin overnight, we are expecting some synergy between developer & investors so that we can feel good about recommending MonyX to our friends and family again, thanks.

**Comment by CryptoGirl88** [comment]
I really, really like your ideas VM4ROI. I would like to emphasize the need for consistent communication with your investors and investors to be. Even if you have to appoint a few good YouTubers with the most subscribers to get your notifications circulating and keep the excitement high. There are a few newer ICOs doing this, and it is working. They email everyone the general message and then give more details to the few who everyone watches. You most likely know the few; and whether you like them or not, they get the job done. It is keeping people engaged and the energy elevated. A win-win for everyone. Thank you again. Monyx to the moon!!

**Comment by monyxcoin** [comment]
@VM4ROI great advices, thanks! I'll forward this information to the team (basically just show them this issue).
